### PR TITLE
Doing math in the code, making one pulse function

### PR DESCRIPTION
**Pull request by georgev93**
I don't have and Arduino to test on, so... baby steps. First off, I'm just consolidating your hardcoded pulse functions into one function which accepts the pulse duration as an argument

### CODE REVIEW

**Review by emailing-files-is-still-better — APPROVED** [review]

**Comment by georgev93** [comment]
Did this work or did it fuck shit up?

**Comment by emailing-files-is-still-better** [comment]
It didn't compile, parenthesis error, but didn't have time to check it as
little dude walked out of the room. Are you using the Arduino ide?

**Comment by georgev93** [comment]
Damn! I am using the Arduino IDE. I clicked "Verify" so I assumed that compiled, but I guess it didn't. Whoops

**Comment by emailing-files-is-still-better** [comment]
Well could have been me too i guess, I figured out how to open from github
desktop and it appeared to work, or you had made a change already

**Pull request merged**
